name = "Eliot Epic Minecraft"
author = "Elioto13"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1a39a97d98f3eedb445726095a86b581f94364cbd95793e5c6b7ba3deb761cc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21"]
