name = "Eliot Epic Minecraft"
author = "Elioto13"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6477f2384319a4f06b7ad5bb713a70f3a0560e98c09a8238f92887db12c2a86"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21"]
