name = "Eliot Epic Minecraft"
author = "Elioto13"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8ef8afe534136aed54fd416f638e409e107909900c27e387cf3d8194347aafc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21"]
